spring:
  profiles:
    active: dev
server:
  port: 8123
  servlet:
#    context-path: /eblog
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
im:
  server:
    port: 9326
